default_language_version:
  python: python3.8
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.5.4
    hooks:
      - id: isort
